version: '3.8'
networks:
  docker-project: {}

services:
  php:
    container_name: php
    image: php:7.4-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - .:/var/www
    environment:
      docker: "true"
    ports:
      - 80:9000
    networks:
      - docker-project

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - .:/docker-entrypoint-initdb.d:rw
    networks:
      - docker-project
